kind: pipeline
name: cicd-image

steps:

- name: start docker
  image: docker:dind
  detach: true
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run/

- name: "docker build helm-builder"
  image: keyporttech/helm-builder:2.12-3
  volumes:
  - name: dockersock
    path: /var/run/
  commands:
  - "LATEST_KUBERNETES_RELEASE=$(curl -sSL https://dl.k8s.io/release/stable.txt)"
  - "LATEST_HELM_RELEASE=$(./latestHelmVersion.sh)"
  - "docker build --build-arg HELM_VERSION=${LATEST_HELM_RELEASE} --build-arg KUBERNETES_VERSION=${LATEST_KUBERNETES_RELEASE} ./docker/helm-builder"

- name: "github release and dockerhub publish helm-builder"
  environment:
    DOCKER_TAG: keyporttech/helm-builder:2.12-3
    DOCKERHUB_USERNAME:
      from_secret: USERNAME
    DOCKERHUB_PASSWORD:
      from_secret: PASSWORD
  image: docker
  commands:
  - "docker build ./docker/helm-builder/ -t $DOCKER_TAG"
  - "newVersion=$(./version.sh)"
  - "docker login"
  - "docker build ./docker/helm-builder -t ${DOCKER_TAG}:${newVersion}"
  - "docker push ${DOCKER_TAG}:${newVersion}"
  - "git tag ${newVersion}"
  - "git push origin ${newVersion}"
  when:
    branch:
    - master

volumes:
- name: dockersock
  temp: {}
